"""Add new order statuses

Revision ID: 091be85ae7f5
Revises: b14635476a40
Create Date: 2025-05-22 20:21:43.854312

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "091be85ae7f5"
down_revision: Union[str, None] = "b14635476a40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE orderstatusenum ADD VALUE IF NOT EXISTS 'CLIENT_NEW'")
    op.execute("ALTER TYPE orderstatusenum ADD VALUE IF NOT EXISTS 'CLIENT_OPENED'")
    op.execute("ALTER TYPE orderstatusenum ADD VALUE IF NOT EXISTS 'CLIENT_CANCELLED'")
    op.execute(
        "ALTER TYPE orderstatusenum ADD VALUE IF NOT EXISTS 'PENDING_CONFIRMATION'"
    )
    op.execute("ALTER TYPE orderstatusenum ADD VALUE IF NOT EXISTS 'CONFIRMED'")
    op.execute("ALTER TYPE orderstatusenum ADD VALUE IF NOT EXISTS 'COOKING'")
    op.execute("ALTER TYPE orderstatusenum ADD VALUE IF NOT EXISTS 'WAITING_COURIER'")
    op.execute("ALTER TYPE orderstatusenum ADD VALUE IF NOT EXISTS 'WAITING_SERVER'")
    op.execute("ALTER TYPE orderstatusenum ADD VALUE IF NOT EXISTS 'WAITING_PICKUP'")
    op.execute(
        "ALTER TYPE orderstatusenum ADD VALUE IF NOT EXISTS 'DELIVERY_IN_PROGRESS'"
    )
    op.execute("ALTER TYPE orderstatusenum ADD VALUE IF NOT EXISTS 'ON_TABLE'")
    op.execute("ALTER TYPE orderstatusenum ADD VALUE IF NOT EXISTS 'DELIVERED'")
    op.execute("ALTER TYPE orderstatusenum ADD VALUE IF NOT EXISTS 'RECEIVED'")
    op.execute("ALTER TYPE orderstatusenum ADD VALUE IF NOT EXISTS 'CONSUMED'")
    op.execute("ALTER TYPE orderstatusenum ADD VALUE IF NOT EXISTS 'RATED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
