"""Fix enums

Revision ID: 1af2e19e995d
Revises: 68be993f86ea
Create Date: 2025-06-07 17:14:27.064536

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1af2e19e995d"
down_revision: Union[str, None] = "a663bd56084b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE currencyenum AS ENUM ('RUB')")
    op.execute(
        "CREATE TYPE userroleenum AS ENUM ('ADMIN', 'HOSTESS', 'COOK', 'DELIVERY', 'WAITER')"
    )
    op.execute(
        "ALTER TABLE users ALTER COLUMN currency TYPE currencyenum USING currency::text::currencyenum"
    )
    op.execute(
        "ALTER TABLE users ALTER COLUMN role TYPE userroleenum USING role::text::userroleenum"
    )
    op.execute("DROP TYPE IF EXISTS currency")
    op.execute("DROP TYPE IF EXISTS userrole")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE currency AS ENUM ('RUB')")
    op.execute(
        "CREATE TYPE userrole AS ENUM ('ADMIN', 'DELIVERY', 'COOK', 'HOSTESS', 'WAITER')"
    )
    op.execute(
        "ALTER TABLE users ALTER COLUMN role TYPE userrole USING role::text::userrole"
    )
    op.execute(
        "ALTER TABLE users ALTER COLUMN currency TYPE currency USING currency::text::currency"
    )
    op.execute("DROP TYPE IF EXISTS currencyenum")
    op.execute("DROP TYPE IF EXISTS userroleenum")
    # ### end Alembic commands ###
