"""Update user table

Revision ID: 1ffaaa63f1f7
Revises: 62ce90a1b5b6
Create Date: 2025-05-03 04:42:31.053620

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ffaaa63f1f7"
down_revision: Union[str, None] = "62ce90a1b5b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "categories", ["id"])
    op.drop_column("clients", "is_deleted")
    op.create_unique_constraint(None, "dishes", ["id"])
    op.create_unique_constraint(None, "schedules", ["id"])
    op.add_column("users", sa.Column("email", sa.String(), nullable=False))
    op.add_column("users", sa.Column("hashed_password", sa.String(), nullable=True))
    op.add_column("users", sa.Column("role", sa.String(), nullable=False))
    op.add_column("users", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.add_column(
        "users",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.create_unique_constraint(None, "users", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "created_at")
    op.drop_column("users", "is_active")
    op.drop_column("users", "role")
    op.drop_column("users", "hashed_password")
    op.drop_column("users", "email")
    op.drop_constraint(None, "schedules", type_="unique")
    op.drop_constraint(None, "dishes", type_="unique")
    op.add_column(
        "clients",
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "categories", type_="unique")
    # ### end Alembic commands ###
