"""Add new user parent_id

Revision ID: 27f549497d07
Revises: 440b14447296
Create Date: 2025-05-22 22:24:39.305946

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "27f549497d07"
down_revision: Union[str, None] = "440b14447296"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("parent_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_users_parent_id"), "users", ["parent_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_parent_id"), table_name="users")
    op.drop_column("users", "parent_id")
    # ### end Alembic commands ###
