"""Add new user statuses

Revision ID: 440b14447296
Revises: 091be85ae7f5
Create Date: 2025-05-22 20:57:08.911057

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "440b14447296"
down_revision: Union[str, None] = "091be85ae7f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'HOSTESS'")
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'COOK'")
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'WAITER'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
