"""Fix telegram id type

Revision ID: 7c33395edb8f
Revises: 1af2e19e995d
Create Date: 2025-06-07 18:55:02.685801

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7c33395edb8f"
down_revision: Union[str, None] = "1af2e19e995d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "clients",
        "email",
        existing_type=sa.VARCHAR(),
        comment="Client email",
        existing_comment="Email",
        existing_nullable=True,
    )
    op.alter_column(
        "clients",
        "telegram_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        comment="Client telegram ID",
        existing_comment="Telegram ID",
        existing_nullable=True,
    )
    op.alter_column(
        "clients",
        "telegram_username",
        existing_type=sa.VARCHAR(),
        comment="Client telegram username",
        existing_comment="Telegram username",
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "telegram_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="User telegram ID",
        existing_nullable=True,
    )
    op.alter_column(
        "clients",
        "first_name",
        existing_type=sa.VARCHAR(),
        comment="Client first name",
        existing_comment="First name",
        existing_nullable=True,
    )
    op.alter_column(
        "clients",
        "last_name",
        existing_type=sa.VARCHAR(),
        comment="Client last name",
        existing_comment="Last name",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "telegram_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="User telegram ID",
        existing_nullable=True,
    )
    op.alter_column(
        "clients",
        "telegram_username",
        existing_type=sa.VARCHAR(),
        comment="Telegram username",
        existing_comment="Client telegram username",
        existing_nullable=True,
    )
    op.alter_column(
        "clients",
        "telegram_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        comment="Telegram ID",
        existing_comment="Client telegram ID",
        existing_nullable=True,
    )
    op.alter_column(
        "clients",
        "email",
        existing_type=sa.VARCHAR(),
        comment="Email",
        existing_comment="Client email",
        existing_nullable=True,
    )
    op.alter_column(
        "clients",
        "last_name",
        existing_type=sa.VARCHAR(),
        comment="Last name",
        existing_comment="Client last name",
        existing_nullable=True,
    )
    op.alter_column(
        "clients",
        "first_name",
        existing_type=sa.VARCHAR(),
        comment="First name",
        existing_comment="Client first name",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
