"""Rename profile to client

Revision ID: 868ceb60a129
Revises: 247b1ec19c9f
Create Date: 2025-05-02 13:44:32.275520

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "868ceb60a129"
down_revision: Union[str, None] = "247b1ec19c9f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("telegram_id", sa.Integer(), nullable=True),
        sa.Column("telegram_username", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("telegram_id"),
        sa.UniqueConstraint("telegram_username"),
    )
    op.drop_table("profiles")
    op.drop_table("items")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "items",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("price", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("currency", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("count", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("is_available", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.CheckConstraint("count >= 0", name="items_count_check"),
        sa.CheckConstraint("price > 0::numeric", name="items_price_check"),
        sa.PrimaryKeyConstraint("id", name="items_pkey"),
    )
    op.create_table(
        "profiles",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("telegram_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "telegram_username", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column("first_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("last_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("hashed_password", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("is_superuser", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "last_login", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="profiles_pkey"),
        sa.UniqueConstraint("email", name="profiles_email_key"),
        sa.UniqueConstraint("telegram_id", name="profiles_telegram_id_key"),
        sa.UniqueConstraint("telegram_username", name="profiles_telegram_username_key"),
    )
    op.drop_table("clients")
    # ### end Alembic commands ###
