"""Add Delivery

Revision ID: 93cf1ce6eaa0
Revises: 27f549497d07
Create Date: 2025-05-23 04:07:38.399342

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "93cf1ce6eaa0"
down_revision: Union[str, None] = "27f549497d07"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deliveries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("radius_from", sa.Float(), nullable=False),
        sa.Column("radius_to", sa.Float(), nullable=False),
        sa.Column("delivery_time", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_deliveries_user_id"), "deliveries", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_deliveries_user_id"), table_name="deliveries")
    op.drop_table("deliveries")
    # ### end Alembic commands ###
