"""Add telegram data

Revision ID: a663bd56084b
Revises: 33d4b6d0f75b
Create Date: 2025-06-07 00:22:39.258504

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a663bd56084b"
down_revision: Union[str, None] = "33d4b6d0f75b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "telegram_id", sa.Integer(), nullable=True, comment="User telegram ID"
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "telegram_username",
            sa.String(),
            nullable=True,
            comment="User telegram username",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "telegram_username")
    op.drop_column("users", "telegram_id")
    # ### end Alembic commands ###
