"""Add order status table

Revision ID: c1daef174541
Revises: 93cf1ce6eaa0
Create Date: 2025-06-01 00:54:36.461855

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c1daef174541"
down_revision: Union[str, None] = "93cf1ce6eaa0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_status",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(name="orderstatusenum", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "start_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("changed_by_user_id", sa.Integer(), nullable=True),
        sa.Column("changed_by_client_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint(
            "order_id", "status", name="uq_order_status_order_id_status"
        ),
    )
    op.create_index(
        op.f("ix_order_status_order_id"), "order_status", ["order_id"], unique=False
    )
    op.create_unique_constraint(None, "deliveries", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "deliveries", type_="unique")
    op.drop_index(op.f("ix_order_status_order_id"), table_name="order_status")
    op.drop_table("order_status")
    # ### end Alembic commands ###
